version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql_container    
    environment:
      - MSSQL_SA_PASSWORD=!nfra48x
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  webapi:
    build: .
    container_name: dotnet_webapi_container
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__RutaWebSQL: "Server=mssql;Database=db_testing;User ID=testing;Password=testing;TrustServerCertificate=True;"
    depends_on:
      - mssql

volumes:
  mssql_data:
